[project]
name = "longmemory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.0.20",
    "flask>=3.1.2",
    "numpy>=2.3.2",
    "openai>=1.101.0",
]
